<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>1.0.0</Version>
    <Authors>One Bear Team</Authors>
    <Company>GoFive</Company>
    <Product>One Bear Platform</Product>
  </PropertyGroup>
</Project>
