using '../main.bicep'

param environment = 'dev'
param apiImageTag = 'dev-latest'
param workerImageTag = 'dev-latest'
param mongoDbDatabaseName = 'OneBear'
param keycloakAuthority = 'https://auth-nonprod.gofive.co.th/auth/realms/onebear-dev'
// Secrets — pass via CLI: az deployment group create --parameters mongoDbConnectionString='...'
param mongoDbConnectionString = ''
param rabbitMqConnectionString = ''
param keycloakClientSecret = ''
